development:
  adapter: postgresql
  database: foofyshrdb
  pool: 5
  timeout: 5000
  username: postgres
  password: password


test:
  adapter: postgresql

  database: foofyshrdb

  pool: 5
  timeout: 5000
  username: postgres
  password: password

production:
  adapter: foofyshrdb
  encoding: unicode
  database: esyasoft_production
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>
